export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

type TypeLayoutProps = {
  children: React.ReactNode;
  params: string | string[];
};

export default function RootLayout({ children }: TypeLayoutProps) {
  return (
    <html lang="en">
      <body>
        <header style={styles}>
          <p>Header</p>
        </header>
        <main style={mainStyles}>{children}</main>
        <footer style={styles}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}

const bodyStyles: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  justifyContent: "",
};
const styles: React.CSSProperties = {
  backgroundColor: "lightblue",
  padding: "10px",
};

const mainStyles: React.CSSProperties = {
  height: "75vh",
};
