import { Notifications, RevenueMetrics, UserAnalytics } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  // title: "Next.js",
  title: {
    absolute: "",
    default: "old layout bundle",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {children}
      <div style={{ display: "flex", gap: "1.25rem", maxWidth: "50%" }}>
        <div
          style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}
        >
          <div style={{ display: "flex" }}>
            {" "}
            <UserAnalytics />
          </div>
          <div style={{ display: "flex" }}>
            <RevenueMetrics />
          </div>
        </div>
        <div style={{ display: "flex" }}>
          <Notifications />
        </div>
      </div>
    </>
  );
}
