import type { Metadata } from "next";

export const metadata: Metadata = {
  // title: "Next.js",
  title: {
    absolute: "",
    default: "parallel routes",
  },
  description: "Generated by Next.js",
};

//----

type TypeRootLayoutProps = {
  children: React.ReactNode;
  userAnalytics: React.ReactNode;
  revenueMetrics: React.ReactNode;
  notifications: React.ReactNode;
};

export default function RootLayout({
  children,
  userAnalytics,
  revenueMetrics,
  notifications,
}: TypeRootLayoutProps) {
  return (
    <>
      {children}
      <div style={{ display: "flex", gap: "1.25rem", maxWidth: "50%" }}>
        <div
          style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}
        >
          <div style={{ display: "flex" }}>{userAnalytics}</div>
          <div style={{ display: "flex" }}>{revenueMetrics}</div>
        </div>
        <div style={{ display: "flex" }}>{notifications}</div>
      </div>
    </>
  );
}
