import Notifications from "@/components/Notifications";
import RevenueMetrics from "@/components/RevenueMetrics";
import UserAnalytics from "@/components/UserAnalytics";
import type { Metadata } from "next";

export const metadata: Metadata = {
  // title: "Next.js",
  title: {
    absolute: "",
    default: "old layout bundle",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main style={mainStyles}>
        {children}
        <UserAnalytics />
        <RevenueMetrics />
        <Notifications />
      </main>
    </>
  );
}

const bodyStyles = {
  display: "flex",
  flexDirection: "column",
  justifyContent: "",
};
const styles = {
  backgroundColor: "lightblue",
  padding: "10px",
};

const mainStyles = {
  height: "75vh",
};
