import Notifications from "@/components/Notifications";
import RevenueMetrics from "@/components/RevenueMetrics";
import UserAnalytics from "@/components/UserAnalytics";
import type { Metadata } from "next";

export const metadata: Metadata = {
  // title: "Next.js",
  title: {
    absolute: "",
    default: "old layout bundle",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {children}
      <div style={{ display: "flex" }}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex" }}>
            {" "}
            <UserAnalytics />
          </div>
          <div style={{ display: "flex" }}>
            <RevenueMetrics />
          </div>
        </div>
        <div style={{ display: "flex" }}>
          <Notifications />
        </div>
      </div>
    </>
  );
}
