import type { Metadata } from "next";

export const metadata: Metadata = {
  // title: "Next.js", // basic
  title: {
    absolute: "",
    default: "Next.JS 14 Tutorial CodeEvolution",
    template: "%s | Next.JS 14 ",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={styles}>
          <p>Header</p>
        </header>
        <main style={mainStyles}>{children}</main>
        <footer style={styles}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}

const bodyStyles: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  justifyContent: "",
};
const styles: React.CSSProperties = {
  backgroundColor: "lightblue",
  padding: "10px",
};

const mainStyles: React.CSSProperties = {
  height: "75vh",
};
