import type { Metadata } from "next";
import AuthContextProvider from "@/context/AuthContext";

export const metadata: Metadata = {
  // title: "Next.js",
  title: {
    absolute: "",
    default: "Next.JS 14 Tutorial CodeEvolution",
    template: "%s | Next.JS 14 ",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={styles}>
          <p>Header</p>
        </header>
        <main style={mainStyles}>
          <AuthContextProvider>{children}</AuthContextProvider>
        </main>
        <footer style={styles}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}

const styles = {
  backgroundColor: "lightblue",
  padding: "10px",
};

const mainStyles = {
  height: "75vh",
};
