export const metadata = {
  title: "Auth",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h1 style={{ border: "3px solid green" }}>Inner layout</h1>
      {children}
    </>
  );
}
