import type { Metadata } from "next";

export const metadata: Metadata = {
  // title: "Next.js",
  title: {
    absolute: "",
    default: "parallel routes",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  login,
  useranalytics,
  revenuemetrics,
  notifications,
}: {
  children: React.ReactNode;
  login: React.ReactNode;
  useranalytics: React.ReactNode;
  revenuemetrics: React.ReactNode;
  notifications: React.ReactNode;
}) {
  const isLoggedIn = false;

  return isLoggedIn ? (
    <>
      {children}
      <div style={{ display: "flex" }}>
        <div style={{ display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex" }}>{useranalytics}</div>
          <div style={{ display: "flex" }}>{revenuemetrics}</div>
        </div>
        <div style={{ display: "flex" }}>{notifications}</div>
      </div>
    </>
  ) : (
    login
  );
}
